apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: squash-db
  labels:
    app: squash
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: squash
        tier: backend
    spec:
      containers:
      - image: mariadb:10.3
        imagePullPolicy: "Always"
        name: mariadb
        env:
        # kubectl create secret generic mysql-passwd --from-file=passwd.txt
        - name: MYSQL_DATABASE
          value: qadb
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-passwd
              key: passwd.txt
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mysql-persistent-volume
          # where MySQL by default write its data files
          mountPath: /var/lib/mysql
        - name: mysql-conf
          mountPath: '/etc/mysql/conf.d/'
      volumes:
      - name: mysql-persistent-volume
        persistentVolumeClaim:
          claimName: mysql-volume-claim
      - name: mysql-conf
        configMap:
          name: mysql-conf
          items:
            - key: 'squash-db.cnf'
              path: 'squash-db.cnf'
            - key: 'docker.cnf'
              path: 'docker.cnf'
            - key: 'mariadb.cnf'
              path: 'mariadb.cnf'
            - key: 'mysqld_safe_syslog.cnf'
              path: 'mysqld_safe_syslog.cnf'

