apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mysql-volume-1
    fsType: ext4
