apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume-1
  labels:
    tier: backend
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/mysql-volume-1
