apiVersion: v1
kind: Service
metadata:
  name: squash-db
  labels:
    app: squash
# target port 3306 on any pod with label 'tier: database'
spec:
  ports:
    - port: 3306
  selector:
    app: squash
    tier: database
  clusterIP: None

