apiVersion: v1
kind: Service
metadata:
  name: squash-db
  labels:
    app: squash-api
# target port 3306 on any Pod with the squash-api label
spec:
  selector:
    app: squash-api
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

